CREATE DATABASE XWORKZ;
CREATE DATABASE CSE;
USE XWORKZ;
CREATE TABLE BTM (  id int, batch_name varchar(10), Sudent_Name varchar(10), Student_Clg varchar(10), Phone_no bigint);
USE cse;
CREATE TABLE DIV_A( USN VARCHAR(10), STUDENT_NAME VARCHAR(20), YEAR_OF_JOIN int, PHONE_NO Bigint, SEMISTER int);
CREATE DATABASE ANIMALS;
USE ANIMALS;
CREATE TABLE PETS( NUM INT, PET_NAME VARCHAR(10), CLASS VARCHAR(10), FAMILY VARCHAR(10));